baseurl = "http://galliard.xyz/"
languageCode = "en-us"
title = "Galliard"
uglyURLS = true

[permalinks]
post = "/post/:year/:month/:filename.html"
project = "/project/:filename.html"
author = "/author/:title.html"

[params]
Description = "Fresh content and links served occasionally"
Author = 'Glen Campbell <glen@galliard.xyz>'
